//#####################################################
/*PROBLEM 2*/
/*
	Each new term in the Fibonacci sequence is generated by adding the previous two terms.
	By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	By considering the terms in the Fibonacci sequence whose values do not exceed four million,
	find the sum of the even-valued terms.
*/


#include <iostream>

using namespace std;

int main()
{
    int MAX = 4000000;
    int a1 = 1;
    int a2 = 2;
    int s = 2;
    int r = 0;
    
    while(r < MAX)
    {
        r = a1 + a2;
        a1 = a2;
        a2 = r;
        if (a2%2==0)
        {
            s += a2;
        }
    }
    cout << s;
}   
